---
- name: Install required system packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
      - python3-debian
      - python3-docker
    state: latest
    update_cache: true
    cache_valid_time: 7200

- name: Add Docker repo with key
  deb822_repository:
    name: docker
    types: deb
    uris: https://download.docker.com/linux/{{ ansible_distribution | lower }}
    suites: '{{ ansible_distribution_release }}'
    components: stable
    signed_by: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg


- name: Update apt and install docker-ce
  apt:
    name: 
    - docker-ce
    - docker-ce-cli 
    - containerd.io 
    - docker-buildx-plugin 
    - docker-compose-plugin
    state: latest
    update_cache: true
    cache_valid_time: 7200

