---
- name: Ensure required variables are defined
  ansible.builtin.fail:
    msg: "Variable '{{ item }}' is required but not defined. Please define it in your inventory or playbook."
  with_items:
    - admin_email
    - bridge_nickname
  when: vars[item] is not defined

- name: Ensure needed facts are defined
  ansible.builtin.include_tasks: 
    file: custom_facts.yml
  when: internal_hostname is not defined or web_path is not defined
  tags: [facts,setup]
  
- name: Ensure DNS management tasks file exists
  ansible.builtin.fail:
    msg: "DNS management service '{{ manage_dns_service }}' is not supported. Missing tasks file: '{{ manage_dns_service }}.yml'."
  when:
    - manage_dns | bool
    - manage_dns_service is defined
    - not lookup('first_found', files=manage_dns_service + '.yml', errors='ignore')

- name: Include DNS management tasks if DNS management is enabled
  ansible.builtin.include_tasks: "{{ manage_dns_service }}.yml"
  when:
    - manage_dns | bool
    - manage_dns_service is defined
  tags: [dns]

- name: install nginx and packages
  apt: 
    cache_valid_time: 7200
    update_cache: yes
    name: 
    - "{{ nginx_package_name }}"
    - certbot

  tags: [nginx, packages]

- name: copy nginx.conf
  copy:
    src: nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    backup: yes
  notify: reload nginx
  when: nginx_update_nginxconf | default(false) | bool
  tags: [nginx, configs]

- name: copy nginx default host config
  copy:
    src: nginx/default
    dest: /etc/nginx/sites-available/default
    backup: yes
  notify: reload nginx
  tags: [nginx, configs]

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  ansible.builtin.meta: flush_handlers
  tags: [nginx, handlers]


- name: Wait for DNS propagation if Cloudflare records were changed
  ansible.builtin.pause:
    minutes: "{{ dns_propagation_wait_time }}"
  when: 
    - manage_dns | bool
    - manage_dns_result is defined
    - manage_dns_result.changed | bool
  tags: [certbot, dns]

- name: run certbot to issue certificates
  ansible.builtin.command:
    cmd: /usr/bin/certbot certonly --webroot -n --agree-tos -m {{ admin_email }} -d {{ internal_hostname }}.{{ base_domain }} --webroot-path /var/www/html -q
    creates: /etc/letsencrypt/live/{{ internal_hostname }}.{{ base_domain }}/fullchain.pem
  tags: [certbot, certificates]

- name: Check if docker is installed and running
  ansible.builtin.stat:
    path: "/run/docker.sock"
  register: docker_sock
  tags: [docker]

- name: include docker installation file
  ansible.builtin.include_tasks: 
    file: install_docker.yml
  when: not docker_sock.stat.exists
  tags: [docker]

- name: ensure that docker compose is installed
  block:
    - apt:
        name: docker-compose-plugin
        cache_valid_time: 7200
        update_cache: yes

  rescue:
    - name: create directory for manualy installed docker-compose plugin
      file:
        name: /usr/local/lib/docker/cli-plugins/
        state: directory

    - name: manualy installing of docker-compose cause we have no package in installed repo
      ansible.builtin.get_url:
        url: 'https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64'
        dest: '/usr/local/lib/docker/cli-plugins/docker-compose'
        mode: "0755"

  tags: [docker,compose]


- name: Ensure /etc/docker/composes/tor_web_bridge/ exists
  ansible.builtin.file:
    path: /etc/docker/composes/tor_web_bridge/
    state: directory
    mode: '0755'
  tags: [docker, create_dir, tor_web_bridge_setup]

- name: Upload docker-compose.yml
  ansible.builtin.copy:
    src: web_bridge_compose/docker-compose.yml
    dest: /etc/docker/composes/tor_web_bridge/docker-compose.yml
    mode: '0644'
  tags: [docker, upload_compose, tor_web_bridge_setup]

- name: Generate .env from template
  ansible.builtin.template:
    src: web_bridge_compose/env.j2
    dest: /etc/docker/composes/tor_web_bridge/.env
    mode: '0644'
  tags: [docker, template_env, tor_web_bridge_setup]

- name: Start tor_web_bridge containers
  community.docker.docker_compose_v2:
    project_src: /etc/docker/composes/tor_web_bridge/
    project_name: tor_web_bridge
    state: present
    pull: missing
  tags: [docker, docker_run, tor_web_bridge_setup]

- name: Generate nginx host config
  ansible.builtin.template:
    backup: yes
    src: nginx/web_bridge.conf.j2
    dest: /etc/nginx/sites-enabled/web_bridge.conf
    mode: '0644'
  tags: [nginx, config]
  notify: reload nginx
