---
- name: Ensure required variables are defined
  ansible.builtin.fail:
    msg: "Variable '{{ item }}' is required but not defined. Please define it in your inventory or playbook."
  with_items:
    - admin_email
    - bridge_nickname
  when: item not in vars or vars[item] is undefined

- name: install nginx and packages
  apt: 
    name: 
    - nginx-light
    - certbot
  tags: [nginx, packages]

- name: copy nginx.conf
  copy:
    src: nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    backup: yes
  notify: reload nginx
  tags: [nginx, configs]

- name: copy nginx default host config
  copy:
    src: nginx/default
    dest: /etc/nginx/sites-available/default
    backup: yes
  notify: reload nginx
  tags: [nginx, configs]

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  ansible.builtin.meta: flush_handlers
  tags: [nginx, handlers]

- name: run certbot to issue certificates
  ansible.builtin.command:
    cmd: /usr/bin/certbot certonly --webroot -n --agree-tos -m {{ admin_email }} -d {{ internal_hostname }}.{{ base_domain }} --webroot-path /var/www/html -q
    creates: /etc/letsencrypt/live/{{ internal_hostname }}.{{ base_domain }}/fullchain.pem
  tags: [certbot, certificates]

- name: Check if docker is installed and running
  ansible.builtin.stat:
    path: "/run/docker.sock"
  register: docker_sock
  tags: [docker]

- name: include docker installation file
  ansible.builtin.include_tasks: 
    file: install_docker.yml
  when: not docker_sock.stat.exists
  tags: [docker]

- name: Ensure /etc/docker/composes/tor_web_bridge/ exists
  ansible.builtin.file:
    path: /etc/docker/composes/tor_web_bridge/
    state: directory
    mode: '0755'
  tags: [docker, create_dir, tor_web_bridge_setup]

- name: Upload docker-compose.yml
  ansible.builtin.copy:
    src: web_bridge_compose/docker-compose.yml
    dest: /etc/docker/composes/tor_web_bridge/docker-compose.yml
    mode: '0644'
  tags: [docker, upload_compose, tor_web_bridge_setup]

- name: Generate .env from template
  ansible.builtin.template:
    src: web_bridge_compose/env.j2
    dest: /etc/docker/composes/tor_web_bridge/.env
    mode: '0644'
  tags: [docker, template_env, tor_web_bridge_setup]

- name: Start tor_web_bridge containers
  community.docker.docker_compose_v2:
    project_src: /etc/docker/composes/tor_web_bridge/
    project_name: tor_web_bridge
    state: present
    pull: missing
  tags: [docker, docker_run, tor_web_bridge_setup]

- name: Generate nginx host config
  ansible.builtin.template:
    backup: yes
    src: nginx/web_bridge.conf.j2
    dest: /etc/nginx/sites-enabled/web_bridge.conf
    mode: '0644'
  tags: [nginx, config]
  notify: reload nginx
